spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.mysql.jdbc.Driver com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    connect-timeout: 3000
  mail:
    host: smtp.qq.com
    port: 587
    username: 11111111@qq.com
    password: bwonpanysgyybdja

mybatis:
    #指定mapper文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml


server:
  port: 9999


logging:
  level:
    com:
      example:
        guixiaoan:
          springweb:
            dao: trace
            Mapper: trace





