spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.mysql.jdbc.Driver com.mysql.cj.jdbc.Driver

mybatis:
    #指定mapper文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml


server:
  port: 9999



logging:
  level:
    com:
      example:
        guixiaoan:
          springweb:
            dao: trace
            Mapper: trace





